---
vi:
  _name: Tiếng Việt

  remember_login: "Lưu thông tin đăng nhập"
  signin        : "Đăng nhập"
  signin_msg    : "Đăng nhập để bắt đầu phiên làm việc"
  signout       : "Đăng xuất"
  username      : "Tên đăng nhập"
  password      : "Mật mã"

  error_signin_failed: "Đăng nhập thất bại: mật mà không đúng"

  error_user_not_found: "Tài khoản '{{.user}}' không tồn tại"

  ## 0xx = other db errors
  #  001: general database error
  error_db_001: "Lỗi CSDL (001:{{.err}})"

  ## 1xx = user account related errors
  #  101: error while fetching user data from database
  error_db_101: "Lỗi CSDL (101:{{.err}})"
  #  111: error while updating user data
  error_db_111: "Lỗi CSDL (111:{{.err}})"
  #  121: error while creating new user
  error_db_121: "Lỗi CSDL (121:{{.err}})"
  #  131: error while deleting existing user
  error_db_131: "Lỗi CSDL (131:{{.err}})"

  ## 2xx = app related errors
  #  201: error while fetching app data from database
  error_db_201: "Lỗi CSDL (201:{{.err}})"
  #  211: error while updating app data
  error_db_211: "Lỗi CSDL (211:{{.err}})"
  #  221: error while creating new app
  error_db_221: "Lỗi CSDL (221:{{.err}})"
  #  231: error while deleting existing app
  error_db_231: "Lỗi CSDL (231:{{.err}})"

  ## 3xx = group related errors
  #  301: error while fetching group data from database
  error_db_301: "Lỗi CSDL (301:{{.err}})"
  #  311: error while updating group data
  error_db_311: "Lỗi CSDL (311:{{.err}})"
  #  321: error while creating new group
  error_db_321: "Lỗi CSDL (321:{{.err}})"
  #  331: error while deleting existing group
  error_db_331: "Lỗi CSDL (331:{{.err}})"

  ## 4xx = user input related errors
  #  400: error while parsing submit form
  error_form_400: "Lỗi dữ liệu nhập (400:{{.err}})"
