# Azure pipeline to build & deploy GoAdmin demo site
# https://docs.microsoft.com/azure/devops/pipelines/

trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

variables:
  goVersion: '1.17'
  gogiter8Version: '0.5.1'
  GOBIN: '$(GOROOT)/bin'
  GO111MODULE: 'on'
  goBuiltAppName: 'goadmin'
  sessionDirectory: $(System.DefaultWorkingDirectory)/..
  projectName: 'goadmincp-seed'
  projectDirectory: $(sessionDirectory)/$(projectName)
  # GOBIN:  '$(GOPATH)/bin' # Go binaries path
  # GOROOT: '/usr/local/go1.11' # Go installation path
  # GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  # modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

stages:
- stage: generate_and_build
  displayName: Generate and Build project
  jobs:
  - job: generate_and_build
    displayName: Generate project and build
    steps:
    - task: GoTool@0
      displayName: Prepare Go env
      inputs:
        version: '$(goVersion)'
    - task: Go@0
      inputs:
        # minimum go-giter8 v0.5.1 for "quiet" mode
        command: 'get'
        arguments: 'github.com/btnguyen2k/go-giter8/g8@v$(gogiter8Version)'
      displayName: Install go-giter8
    - script: |
        g8 new --no-inputs file://$(System.DefaultWorkingDirectory)
      displayName: Generate project using go-giter8
      workingDirectory: $(sessionDirectory)
    - script: cd $(projectDirectory) && go build -o $(goBuiltAppName) -tags netgo -a
      displayName: Build project

- stage: test
  displayName: Run tests
  dependsOn: generate_and_build
  jobs:
  - job: test_sqlite
    displayName: Run tests against SQLite
    steps:
    - task: GoTool@0
      displayName: Prepare Go env
      inputs:
        version: '$(goVersion)'
    - script: |
        export PWD=$(pwd)
        mkdir -p $PWD/temp
        export SQLITE_DRIVER="sqlite3"
        export SQLITE_URL="$PWD/temp/temp.db"
        cd $(System.DefaultWorkingDirectory)/src/main/g8 \
          && go test -v -p 1 -count 1 ./src/myapp/
      displayName: 'BE: Run tests against SQLite'
